# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: default
type: Opaque
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:OSG1yhfw5FhZXZIvCjWnxtRx2JYUd3GESyzDtJrmrXrAxRdkvB0HuI8ttM4YC47osD+u7KCqNaDRCBvV3dXJeAP/giBhhAH/TGqmT7craEWJMR/XCUB8RoN8Zi8X1CIHxO9jfcOKNs/8GDnOwLxktIUjvMYH+IfSiw7S/tYCbsEHka4/S54=,iv:293kiChdwuqWzJSulFKZIidtL/x28CfoV3VNnU0hHRQ=,tag:Ua4mKpveAEylKUUPWNRJXw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:TbzT9LwkeMdzYIiJPNj28BXzgsqcKWPt2wqTxfRwqZLXfRCWeGEKWSqQIu65yIAilF8WeDxLIqSQQz4afNvbXUVQgrrAApux1m/a7jnyflUWDqS6FJhRqY84Sn6MDOgBVcCaCoJ4tr7uHw==,iv:Hi2aGKt2tH67vuwg49YSWL1CnOGtVPj6mksN2+r7e2A=,tag:MOd8hQeRTTjhqHYFtdHPEg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:xXdIY531N2TOJQ0=,iv:5I4M4giJTPGi1Jkmj4bFCsKdbA19F4FWu+IcliTRE7I=,tag:p6887FGkIAyXcJBMo5FS7Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:5u7WRk2yjNqEr/0REgI3iYYiJGaW847U0X3QZe7O1y9ZZT760sc=,iv:RVQKzjs0FZD0s4rHQfFeTpkw1OhlfUcTDEXS/DkctYE=,tag:3Jk1SsjqFJU/aIXvX4EEqA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:PnsNstTU9bPBxm8=,iv:4xq2WKGYN4hD+z1QdS3bhLb7HelwAHl5LKn53ClnUHA=,tag:1pJxGwjrZBjXxRiMO+k7Hg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:8BXthaHNSoptR5vqH900yGcbzejc3mCEkaww+DKWdzQ=,iv:KOJ2vI2dnQQU2CB69wuHZQDZUEOAmhC+z4qxRO1/T7U=,tag:MEA4gUPQgRNmPHMKiNcsbw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:BEIt7P7mGulBoltZ8vqkH6MQNIqxxDqNybnXqknY3zw=,iv:+f298aBswsFg7Bx8JNcjzPmmAwFxQeyS3wedxBa+sG4=,tag:EwruKLaUXzFqjMhsd9LI/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZzBPOVlpOTd4OVJLQTla
        ZUFUWGlEQ1N1a0wzN2VGM3hYQnFNRzQrOVdnClRSODhMZUZ3OXF1TjhhS2I3ZFQ5
        TXdsNUNpRnZCSFg5NExCMWVGRDY4UUEKLS0tIFE2VzRndnlVczZQWnlMNUU1c0kr
        VUFxNUVEWmtQVG9xSUNzM1BYd2RFT1EKCPOzTUQgkGnR6hFn14+sj3oOwglsZwEs
        ZoMmyfveyjR5Qol7R03RCv+ykUZIB13JAEQ+yIco7ZfuH4dpdhxA3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdnd5M2J0cmY0N011QzhS
        ZHB0VFBMdktodG1PWE1HZlN1UittMnlQendNCmVjZW5salpaVTFSSWp3Qno3NFZj
        aWdOcjluaEJyMTlEUjcwQUhocDQrRVEKLS0tIE5QUXhuNjFCQ2dhbUsxdzdxNUJ0
        dFVYV0hjTGVDdHlKZ2xRTzlldC9ta28Ks3nvgpHIfXHAacHebwETioivO09cKRk+
        9yVaXDSA/ZBRm9vtiaXY13BosmJrjICjZmp1s+72r5XfilVUsG9bPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-21T20:20:24Z"
  mac: ENC[AES256_GCM,data:L9Hg0/GAbjO5O14LR8jK4Ni8UBAa4HoUjZ2zl4jP7ZnjXVoGSOA35lnLFwLvAJGmu9LMz/+p1T0/P5JEoh44jpNiv3D9d9dnzQl3a5Qg7p/RE25HXl5uwaHOOOHzc1nf4POdwoew9uTlct3SvExuIqksBe6K0YOFMEmPMC62JQc=,iv:94ye/j6n3jMuJ5sVlMKS8aAK+nLsDSYqsTLV+9EDFBw=,tag:vkVesbNOld0Iz5ow1Y10Uw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
