---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      ollama:
        containers:
          app:
            image:
              repository: intelanalytics/ipex-llm-inference-cpp-xpu
              tag: 2.3.0-SNAPSHOT

            command:
              - sh
              - -c
              - >-
                mkdir -p /llm/ollama && cd /llm/ollama && init-ollama && exec ./ollama serve

            env:
              OLLAMA_MODELS: &modelPath /models
              OLLAMA_HOST: "0.0.0.0"
              no_proxy: "localhost,127.0.0.1"
              #DEVICE: "Arc"
              OLLAMA_INTEL_GPU: "true"
              OLLAMA_NUM_GPU: "999"
              ZES_ENABLE_SYSMAN: "1"

            resources:
              requests:
                cpu: "2"
                memory: "4Gi"
                gpu.intel.com/i915: 1
              limits:
                cpu: "4"
                memory: "8Gi"
                gpu.intel.com/i915: 1
            securityContext:
              privileged: false
              capabilities:
                add:
                  - SYS_ADMIN

            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 11434
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup: *probe

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      models:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: "openebs-hostpath"
                resources:
                  requests:
                    storage: 50Gi
        advancedMounts:
          ollama:
            app:
              - path: /root/.ollama
                subPath: .ollama
              - path: *modelPath
                subPath: models

      dev:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - readOnly: true
