---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
spec:
  schedule: "@daily"
  immediate: true
  method: plugin
  backupOwnerReference: self
  cluster:
    name: postgres
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
