---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      qbittorrent:
        initContainers:
          coredns:
            image:
              repository: mirror.gcr.io/coredns/coredns
              tag: 1.13.1@sha256:9b9128672209474da07c91439bf15ed704ae05ad918dd6454e5b6ae14e35fee6
            args:
              - -conf
              - /etc/coredns/Corefile
            restartPolicy: Always
          gluetun:
            dependsOn:
              - coredns
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            env:
              DOT: "off"
              DNS_ADDRESS: "127.0.0.2"
              HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: &gluetunAuthPath /gluetun/auth.toml
              VPN_TYPE: openvpn
              VPN_INTERFACE: tun0
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: 80
              FIREWALL_OUTBOUND_SUBNETS: "${NETWORK_K8S_POD_CIDR},${NETWORK_K8S_SERVICE_CIDR}"
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            restartPolicy: Always
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2@sha256:a724f86a39fa637fc4ff81165585d7273dc9dcd9ca59818a34e9fa9c467dd26c
            env:
              TZ: Europe/London
              QBT_WEBUI_PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: *app
        primary: true
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
          - qb.${CLUSTER_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: qbittorrent
      media:
        type: nfs
        server: cappuccino.internal
        path: /media
        globalMounts:
          - path: /media/downloads/qbittorrent
            subPath: downloads/qbittorrent
      gluetun-auth:
        type: secret
        name: qbittorrent-gluetun-secret
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: *gluetunAuthPath
                subPath: auth.toml
      coredns:
        type: configMap
        name: qbittorrent-coredns
        advancedMounts:
          qbittorrent:
            coredns:
              - path: /etc/coredns/Corefile
                subPath: Corefile
                readOnly: true
      tmp:
        type: emptyDir
