# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-config
stringData:
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:9h2fVJO2BQ7hnQR05kVF,iv:6UDvu6cAbERSzLOWdHfEJvs7ZumbSQWa6hh7hXRxN1I=,tag:kqXADcsbkCvJ8uM0h1AIEw==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:34UHshB+/l4avkrN67KJWygpXk9Ys2634SWFB8nOjzV5fQQRsYWtSmJRiz4=,iv:Sc8B22DTnQ8qlLCpKy0E4BsSVYMXbrqZOUn28UzZbGU=,tag:Pm9KEWO0Hva/0XDGIeKKaw==,type:str]
  SERVER_CITIES: ENC[AES256_GCM,data:988MhgFj,iv:8+fkFo4qyOpL7vQVeGh3bDO0ChW/c/MuJf9eJWeuLa0=,tag:5Et+oBoq3JL7M6nsyB0oaw==,type:str]
sops:
  age:
    - recipient: age12na74smcu3ww2gaglv8spqwur29d7gqax83u00w9rs0t0yw2eqlqc249je
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRndJWnNOU2JOSGpVRUVz
        TzIrVndXeExnUUx0QkZ4UmhBLzErenJGNlFVCnFqZVlYNGlvRC9GbStHYkxjc3pl
        UjlzRTV1SUIrSEhia2FoajVHMDFPLzQKLS0tIGdDUzNxd21DRWYxQlJJZ3ZTVWpa
        NnNnV0tqY1hzSGZkNG5rT09wZndvbFUK4q0TnhT3rdyaPoeYuJ4S50pxCp1b8OsW
        Q9p6klGlUv5h2lXq6yIs6DDv1Xdfqb1b5B5uTaV7TNdD43dBS1G9ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T15:41:16Z"
  mac: ENC[AES256_GCM,data:weXoMW/cJQZwjoXZ41yZSeYf3N+Rs6mchTVf0Gvs+HGJerKteeGmgO6d1V/MPY+dIo7xE3mX5k6MCue9cC4aVhM4y2ow1xh6AO3vSrVnu7+iD18LxHLgp/m/zON3uORfyhtuPk5vLYcHVtIBb1fFe0bBe5E0y5URTmP75Wc+BEw=,iv:YgHdfXJ/odP8SllcQJbgEvd2jMCPOHmNGL+AD+4sWQY=,tag:0hKM988c5YPygy/l3yW1YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
