# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-secret
  namespace: default
stringData:
  OPENVPN_USERNAME: ENC[AES256_GCM,data:8WpFzr9kM3DzAZQjM4NLyC9D2I0=,iv:3lh1kGjypAjJvaycgZfNdaHfq55Mzo55MaJbbQyQ2Q8=,tag:yT6lUDRHCipho8copOEF3A==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:NZfG5rgq+P9V1aw4PAnRpE7gh1P3kEhs1JdQ9x2mbEs=,iv:MTweDsQACBuIKrTNFBCemyGtrtt+gZqFCkFIn9hGnGw=,tag:ZyF3zNj7HROS8EG47SvUsg==,type:str]
  PORT_FORWARD_ONLY: ENC[AES256_GCM,data:4ddwtA==,iv:79gMs9RcnaPxyh/Rw+8twianoLPI/n3MJIPFHFjVV+g=,tag:n24OKk+gNjhghLmucdkzGg==,type:str]
  VPN_PORT_FORWARDING: ENC[AES256_GCM,data:JSU=,iv:h/TsHh0sDkudrBYrrd8UPJrbOt/SnTgelN3uQ0yr0GI=,tag:42G38dKqDac3f57c1z/Txg==,type:str]
  GLUETUN_CONTROL_SERVER_API_KEY: ENC[AES256_GCM,data:HfihDo0X877vD23DcLTv6MnPZKL2Krc/CM1KUTA5OYg=,iv:rJdXJMELTdjnk2baceeRlKVOHsCib6ng8jdiMxo53Mk=,tag:l/FI/Wbmk3W7QWHGM98ybA==,type:str]
sops:
  age:
    - recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneXpobUV1VnRVeURzVlVp
        UVNVRFkvUnROOHpOeCs1Tm5kQmRKNW0xTldrCi9WQlNIWUQ4NHNtNmx0aWI4OEhP
        RG96OWxqUk9QM0NYUFREbWcwMzd0WVkKLS0tIGNlQ0YvV1dDcTBMcjIvenB4WTNN
        M3o2UUpXZytSbDdocGVnQm9EdjY4UlEKpoY4ZVmRYPzwIxhEwJAYfXWmKpA+Lt9F
        l6i9yqKsroj2f//C3nvH+j8whbbWru5cZKbsl5WLYEZ0ynRtjuwiOw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd2FaV092Y2lxZkdhSVNE
        M2pma0pBamhaUmExSWd1YTUzNnZkTmtZdTNjCndURTF3cnp4NTJrSGJqM0RNSVRu
        YlY5ZWkvU0hwUDN2aEJYS3c2WUp5Sm8KLS0tIG45ZUU0WkN1aHgwUnpLSm5rcVRV
        TGNxSm9hSXNkZWx5c3RZQ212ZFF0dUkKR7SYU33aj9pXf6de2nrAKB5h5IVwUXrZ
        NwrmBY8v3IiBphan9DlgmF6nT1jaxYn7g1100xZz6JanrP+wLV6Qcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T19:46:04Z"
  mac: ENC[AES256_GCM,data:whYCfurl5x0hUUALxjX7QSD/gVCQBns2ljxDarVhUXJuOMyuBBuh4ewrv4UtW04cdB5g37o5eIbmi6NXaQSxHoga+jhEH7AZJ+8LXCTVziaLba+z9Sb0elD6ym9d62GiqemhUL0m3iyKQc1fbreZwQgc/Mb+Vn1lFkyc2+ec0V0=,iv:yFpyXV9zShos+Q5f5QAw8uZxIe/+q5yrbEysbcmayao=,tag:95ySoMDUBJc2CMJgRj4qqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-gluetun-secret
  namespace: default
stringData:
  auth.toml: ENC[AES256_GCM,data:RrLWzqIthTx+vISe8i8s9O6U0s6stWRCb2sh5Bx9h11Rik++84QLGIdu6dQFVas/UFi28S7nX2mNaq3L0du/ooEHdDRFnVWveQoaJGMxf53zBKP0nMlpeoszWYsNzTFNotVO7qRxQG1Z75BW+5P5QfsJKMWvzoJefTrsvt4O1qOj+IuBOnuWctbVef8349k063VV8cZiUdo70oZdslPvykniWArYQd62F1jQSg==,iv:uezw2TNU3wIpIwX6ZayuMaAB+4mr3GNS5peDdMld/L8=,tag:OY2patR5xcZm63CX+4Y6ZQ==,type:str]
sops:
  age:
    - recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneXpobUV1VnRVeURzVlVp
        UVNVRFkvUnROOHpOeCs1Tm5kQmRKNW0xTldrCi9WQlNIWUQ4NHNtNmx0aWI4OEhP
        RG96OWxqUk9QM0NYUFREbWcwMzd0WVkKLS0tIGNlQ0YvV1dDcTBMcjIvenB4WTNN
        M3o2UUpXZytSbDdocGVnQm9EdjY4UlEKpoY4ZVmRYPzwIxhEwJAYfXWmKpA+Lt9F
        l6i9yqKsroj2f//C3nvH+j8whbbWru5cZKbsl5WLYEZ0ynRtjuwiOw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd2FaV092Y2lxZkdhSVNE
        M2pma0pBamhaUmExSWd1YTUzNnZkTmtZdTNjCndURTF3cnp4NTJrSGJqM0RNSVRu
        YlY5ZWkvU0hwUDN2aEJYS3c2WUp5Sm8KLS0tIG45ZUU0WkN1aHgwUnpLSm5rcVRV
        TGNxSm9hSXNkZWx5c3RZQ212ZFF0dUkKR7SYU33aj9pXf6de2nrAKB5h5IVwUXrZ
        NwrmBY8v3IiBphan9DlgmF6nT1jaxYn7g1100xZz6JanrP+wLV6Qcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T19:46:04Z"
  mac: ENC[AES256_GCM,data:whYCfurl5x0hUUALxjX7QSD/gVCQBns2ljxDarVhUXJuOMyuBBuh4ewrv4UtW04cdB5g37o5eIbmi6NXaQSxHoga+jhEH7AZJ+8LXCTVziaLba+z9Sb0elD6ym9d62GiqemhUL0m3iyKQc1fbreZwQgc/Mb+Vn1lFkyc2+ec0V0=,iv:yFpyXV9zShos+Q5f5QAw8uZxIe/+q5yrbEysbcmayao=,tag:95ySoMDUBJc2CMJgRj4qqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
