---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nextcloud
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.4.1
  url: oci://ghcr.io/nextcloud/helm/nextcloud
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  timeout: 15m
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nextcloud
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      flavor: fpm-alpine
      repository: nextcloud
      tag: 32.0.0-fpm-alpine
      pullPolicy: IfNotPresent
    nginx:
      enabled: true
    nextcloud:
      extraInitContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:17.6.0@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
          envFrom:
            - secretRef:
                name: nextcloud-secret
      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.database.svc.cluster.local.
        - name: REDIS_HOST_PORT
          value: "6379"
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        smtpHostKey: smtp-host
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
      host: cloud.${CLUSTER_DOMAIN}
      mail:
        enabled: true
        fromAddress: ${SECRET_SMTP_FROM_ADDRESS}
        domain: ${CLUSTER_DOMAIN}
      securityContext:
        runAsUser: 1022
        runAsGroup: 1022
        runAsNonRoot: true
        readOnlyRootFilesystem: false
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://cloud.${SECRET_DOMAIN}',
            'overewritehost' => 'cloud.${SECRET_DOMAIN}',
            'check_data_directory_permissions' => false,
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '${NETWORK_K8S_POD_CIDR}',
              2 => '${NETWORK_K8S_SERVICE_CIDR}'
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'trusted_domains' => array(
              0 => '127.0.0.1',
              1 => 'cloud.${CLUSTER_DOMAIN}'
            )
          ); ?>
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'GB',
            'maintenance_window_start' => 2,
          ); ?>
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
        www.conf: |
          [www]
          user = www-data
          group = www-data
          pm = dynamic
          pm.max_children = 57
          pm.start_servers = 14
          pm.min_spare_servers = 14
          pm.max_spare_servers = 42
          pm.max_requests = 500
          pm.process_idle_timeout = 10s
      hooks:
        post-installation: |-
          printf "Add missing DB indices\n"
          php occ db:add-missing-indices
        before-starting: |-
          # disable unneceserry apps
          for appname in activity circles systemtags federation privacy \
              nextcloud_announcements announcementcenter support survey_client \
              user_status weather_status dashboard
            do
            php occ app:disable "$appname"
          done
        post-upgrade: |-
          # based on https://github.com/nextcloud/all-in-one/blob/25c580bca370eaead5f1fad9d3842a9c49562dff/Containers/nextcloud/entrypoint.sh#L451-L457
          php occ maintenance:repair --include-expensive
          php occ db:add-missing-indices
          php occ db:add-missing-columns
          php occ db:add-missing-primary-keys
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres-rw.database.svc.cluster.local.
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: INIT_POSTGRES_USER
        passwordKey: INIT_POSTGRES_PASS
    ingress:
      enabled: false
    persistence:
      enabled: true
      existingClaim: nextcloud
    # this seems to be required for nextcloud initialization which takes a long time
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
    securityContext:
      fsGroupChangePolicy: OnRootMismatch
