apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  RESTIC_PASSWORD: ENC[AES256_GCM,data:WHgjfYmT2Dr0Ar6URcK6LL8CJ3ZQ611qY8RWjRKh4y+If0dD1zn77POjPZcMIMRFOvOM98sj/xp7VZQlarKZhA==,iv:3bUd/uFY1ElbkCYph5K7+3fx1Q7X2YhUZiclzrCkp08=,tag:WMCzLwhTc9ewfjiyC1co3A==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:tutv+TSnRknvNXVMWHOEFNhH,iv:3UuZR8yZW8unRSIKyJ19kMj6e/D8eVsoByCiba6J1E4=,tag:QLjFU6esl2rL02aLP142Vw==,type:str]
sops:
  age:
    - recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL3ZRRzdPRlpLdWdYdkxK
        b1hnZEdlVW00d1UxM0c1cFE1RE40OXp6bFY0ClNYbnREcW5FUlptVGpha3dJUDUw
        dlpHUUJBWlFUc0p4ZnJ0R2t4Z0Fob0EKLS0tIHdvYm5peHdEaGExUWp5RFpqYUNC
        NURsZ2owMm1tczczbWc0ZWFBSUVQV2cKNhD8KpD3ddtkje6Peg3QccmSK2zvL5bh
        NZ7K/DPpUYl1kMtdxq4Rtj4LFKmpoox3i0Mdib3DgT0MtOFRHtCM6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-20T20:00:26Z"
  mac: ENC[AES256_GCM,data:7+QJtVYPh06zpa/cDHaM5nC6+TGz9g/3zgYIZaiCCJ6z/vsT6RzsyZFBvGyF/HmncUo+m3xlix0Lp2KBQH0RWD3c1rJ51pPUaINsu+GdPsQgKpA9N/IvK9C5WOMwTPxnIn7Ouz69SRFOPCyxiBeN+quo3AuAbYCBARqWSEWncso=,iv:x45yUwfuL97JQ4r8rY4qg9Zi3JYwUOO/TK3185IF/1M=,tag:OI9bNxHR4W2uSgFibbKdYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
