apiVersion: v1
kind: Secret
metadata:
  name: dawarich-secret
stringData:
  #ENC[AES256_GCM,data:QS3mLjSP1LVZ,iv:4ywrEmnnqFHdoSjtPlLOwiDPYYvYyNpWeqdfMEIlBAs=,tag:XcgXhkGlTWsJH26NqBYM3w==,type:comment]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:sEunVUKk5XI0ObcO4RxZO2KzJwAwXEntkvm95XbQWDjYQ1TOLIqHhjbPNQTygM3ZNYVFZCE1PtO+pd1Bkyn/0w==,iv:+m0/kji2uZ1ZLOEQl+CNqXuEoYnSmSzC7dD8rs7/NRY=,tag:LPXyaes+N+Wamy+I7EJ32w==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:/uRUo0Ye4YTi6ClbmiZgPc8LBwYP2dn6XR4s+s6Oue52jz9pnAI4d4CffrfUyVyd+A==,iv:ZcZQVUY7+Xs0VwpjLKkGX4AcrXHQlm4GP9S7F6vgP5U=,tag:PDJrOQx2BQmI+qMMgA5kdA==,type:str]
  #ENC[AES256_GCM,data:C0Np,iv:K0xeQy8mrv9Dfu2dTmLyERtzUPXYACaaFlfr5wo1z6o=,tag:Pz8gdRbgI9EstH8BwT80eQ==,type:comment]
  DATABASE_PORT: ENC[AES256_GCM,data:Yolruw==,iv:of9BI3/lffOUIotF7/C2tCGWEbmpQNK474X8o+VgFfY=,tag:pSpDw9a4yN8vidJPAaOmIg==,type:str]
  DATABASE_NAME: ENC[AES256_GCM,data:7vwfyK9Cup4=,iv:toFkDuShM0oVgnOeHuCbUPRjvq23wwBh2JfbuYkNM/4=,tag:IHIrBz5SS8hG3EmzVP/Rrw==,type:str]
  DATABASE_HOST: ENC[AES256_GCM,data:4rouSVqzbcm6y9diFNAGCerORuoqntB9YHqPFwwAqzlErKqxkXs=,iv:VsXmAIdNYOT3DIThIG0zzkN6c/yKUGlVed78+kXsHtM=,tag:ulAoet5BtbBRkk6SNai06w==,type:str]
  DATABASE_USERNAME: ENC[AES256_GCM,data:09/QBFNP7SE=,iv:5wSdAba2VbA8bJzr7q9EHOEtv3pMw0ybgysutoL/LEw=,tag:plvFw2ryFrFelfBLbo6fcQ==,type:str]
  DATABASE_PASSWORD: ENC[AES256_GCM,data:pZw9N0LmxknXk5SesjDhJapeBzlTCDLI3giQnK43PWk=,iv:XirWasj8uA3kGhh/yNvfjqrVuK6wxL8s3PdYK7iZXIE=,tag:8ScTH5yw8K5QYSni5qLTyQ==,type:str]
  #ENC[AES256_GCM,data:GU8gRfN77mA=,iv:t3kZZYK8UmS5t3hVtSFibAnW4GmPNvwIrQVBmEoGuXA=,tag:EEO7bAR3ipQ6UdTeqVjb1w==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:u1TPfvgAmus=,iv:z1EgZ4G2FhgnyJ1Y/MCC+c/BskFvr5RgER2FqocZWVk=,tag:3l1+KU7IeJzfkXiMTsYUIA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:pf3UH6FnAD5K3zhfFvd7JCe9Ue+ATbw9J8LhI6f1sjxNCc0WXec=,iv:IDlRyMPNakCrM9EwgSYza5gEU7SHNRsVSvVg/s09Fw8=,tag:jmrf7UQmXDs29y6Alc6pJQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:a+wVj5ErK5Q=,iv:exvqTMsckEHLCYEx7cOVoMQUBV54DCm2DkyH/E1TXWU=,tag:4IZL+hjVrCjqA7pbYuizVQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZLnuWZ6uhfAcJfCtpqZheFrh9Jmgf3H5e3Fv9JNyXVQ=,iv:qHX2WuAwWYDbcOJRpfWlc07BxmwJQUuh75pRhHQWhxk=,tag:ZZomZ+9yPyNxf6s73iJVQQ==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:VYg=,iv:EzEcp01RTenkAIX6vehFBJJIQhEerB69lUJsLtV3rtA=,tag:SaOlq2ErvatAA/JIlLtzrA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OEeSksOx9eaaCw7+6KWDc0Drt/2FJ1VwMOK4ID53XYo=,iv:dBMfvO7rfovPRJQCJiSrxOCBgNDZTcFI4xlh4HXzwLM=,tag:tLFauOw2V/LKRAMVuCqkOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNG50TlJRMTF2RHZURUJX
        OThWQWgvVjhzU25ScXN4QmMrWlQ1aTE1Vmw4CldacDBDNlhQekFZRzhPV0tPVVVy
        VWhrRXJzMktGQ3JNWGZ1bk42SElPQ1UKLS0tIE5iQXJkREw3Tkx2Q1ErcFJ5Uk5P
        Q1h1U3FFbnN2NVlzd2hhZ0hNcHEvYncK/9xS8Gc3uSmQAu7duuQC9sUKINIggvRK
        4uUaNbOBTWwxgwuqysfQ/6hJhBTfqXCaoCkTZnCQexPLyXi6Ym8ohw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTnhXUWV4U1hkM21MZW5H
        N0s3SnMxM2NlSmh3MHBQNTdWY1VkTXg5NFFRCkYveGNZc0JxbG5MbytjS1RVVnNw
        empWaitMd0tKdE9qaGErVE1YZTJ5a28KLS0tIE14eUZUdzV5VnhVdDZYMkxJK2lC
        ZzQ1OTZBcWRBcXZ6dzFJVXp5Sjg1SWcKf+ITl3CQqXIiYy8DxUQVPpBVXbvP7QW3
        RSoHIkiCuU7dicuknpqBKCOZyA6Nh3+CTKFg8f2qlmLc86kPuytHWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-04T17:41:39Z"
  mac: ENC[AES256_GCM,data:4+tkieChvXliuVC0YOtuCuyTbXpBlwIOjGLM9sXVXIIHWcNn+sk4VLPNhYl4e+2XJX3isx34eNyK1UwkPMqhWbss6dqI2Q/Z66JzyaXSqosFGJSBLl1KsJGVs5pvdmwOmD0UEFFAXVPsrL3zBYWKjQ3xtA/xuqqrgHsA5mDl2uQ=,iv:tL8fPYz+0eKcta73arboDsIFf6xf9iN5T9jIof5NaqM=,tag:MRCJLSrKfVbWqExNF0D0YQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
