# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: grimmory-secret
  namespace: media
type: Opaque
stringData:
  MARIADB_PASSWORD: ENC[AES256_GCM,data:1N2jlXnUJ36QU66QXhwZWT6EPOrnVRQo9kyq/bAnuQs=,iv:E9zxrzasb08eNph21obu7WVanyvocT3QyztdND9Hq7g=,tag:CpcxTUdBQbNEYaNXNOIXEg==,type:str]
  DATABASE_PASSWORD: ENC[AES256_GCM,data:oDFqRqaSo7g6HgR88sRsRNjrm6rytYWqrMtv7Vr5AxY=,iv:hYRxJqcy7Y/Uaa8V0WBYSMmvUqaudLudg4+6U5Nxp7A=,tag:IsPhiCO//VvLiAMluN2Ngg==,type:str]
  MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:OltsGivZYVYb2Nn/Nkdrj9c03KGPWOOHD27HoP6zxrc=,iv:EK00572j7AgjitM1H0UtoUI+J4ZSMq4rIDm4kSXD+Ho=,tag:o7S0LyO5mEhVlx6wMaq3jw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd2ZTeDBwOU1KU2tkVWtR
        MVlDeDdhQlZSb3gxaGp1Y2xzWmN5UjVERnpBCmtETTRHMC9iN3NZQUtxSllkT2N0
        dDRXZ1NuTG4zZ25qclVvVFYyMzJWUkkKLS0tIHNmbnd2NDBFWU1jbUNZZEVKYURs
        ZGdvU2lUWlRIb2Zxb0Y0SUw2RlNvTmMKz17Ew+ZL9ZzX4ZJWmQtn4N0MQePLuTIr
        fwTjs7wgxHUBTXqzKkAB6hbi5XxszJzA76XLxHnUddPpBXODlNswmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSDdpRWc5QkZtNGZZNHpy
        a3NDRnE5dmltYkZNa2Zjaks4UTlVdE5CbHd3CmZjZXhxcSs0Ky9EaXVQZ2V4dzR0
        dWpVQTdmLzdlSFVkVkhoRFlmQjl1Q1kKLS0tIEtqUWUzbHJNRTIrWXVqR1VVdDFR
        NnhkK0daMno4ZW1GS2IzbWxiWE9ManMK8ydVyiKo5S5ymx5O/0sZaquqRVdXY9rF
        DlH9hityqEtVssGbuuF+mHT9JtxOdnWS3jvbDRO0gjXB9wN54xM1rQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T18:39:35Z"
  mac: ENC[AES256_GCM,data:0Scsp4/msRdMQaqOfGe9FhRR7/cgJh0aBW9BXrZV/NDewhvbjV2cOhDww99SNBK01HlgvYBxdAJBqhPE0k6MML5kLFNH5VJXWuNGulJrS/xMAMffMGtFxDNiaxscyAtTOKgpruq1rzc2ZymBpaT0Xojb3IjoCsbmNdVOkEXo/XA=,iv:JTGUn/eJ5Mn3lVGl5Miw7RVHtFNZF1SCjfj9kUvFUd0=,tag:TywUyTlwDgupFhvQM1MBvg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
