# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: media
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:t2FciVH69ywHo1IVgXUH6txdy5PkDrxk4rI7K5WXupg=,iv:GPppVFC38ljIV7wyvNaHJg/OF+TLIg4eExTkWlGGCqA=,tag:hB7VxNJU05fjLyc+oVAncQ==,type:str]
sops:
  age:
    - recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY3JndFpPendGVHFZSVZj
        K1ZoNXhPVTYvNUtLTTVXQmZobTY2U0RuYXlzCjJRTTFLWG01SGJIS2VPdHVDdUda
        WE5qLzhoMWowVnV6NWNqTjRmdkg0VEUKLS0tIFk0TTE0TVVsbDJJUmJHTnFpTXBN
        TWxHdU5TcDFGNzRvVE5BTzB3am55ZEUKfxD9VVoEmKGN/xu0blXU9RVnZ8QTA3Pq
        qeZ8hc9SscoGqKZ1S7zzF7rDQPr9x1zaHq2n0uZcvXsDApQLWqHRHw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd2hDei9kME1PemlYWUw3
        bTdyN1pwdnhzcEZHclV1dHNwM0FtOXgvT1FjCitxdkRDT3lzK0hVam1lTFVKcnR2
        b1M0NWJuZkU1VDF6Y25HYStHbWZSL2MKLS0tIFl1MUxZWDB0SitlY1FLZnVXcnFu
        VVhSM0ZBWE5PZTZhenJieWtyRmtBSXcK4510aR1rBHnxXlxjpYVp8P9EU3Kc7ymT
        9ky77LA/d/ZLj0apftdCEWdf3NO0OBCOR/5piF6SGTPYGOvcM8T+og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T17:13:55Z"
  mac: ENC[AES256_GCM,data:aFXzoJVm484ob2pRHlOuoTQokYa9QjqYOSM6xzpdjPsPbnF0/kaQef6dMpxDmk5rv5Wimy+3WDfUOKW3jQTgr4kSTMDLxrCTQmdPdbcWtXqlR6/K/Dpwz/4Bup+CWQ7VSBD9AMpIxrJX2lJj2/LCb0K24rlEpebuBVjup9AbzpE=,iv:giafppzghDuXOOCTB3W1wwHHU+4USjm/e83JVE85UME=,tag:wwlgYG0mSqrPlBCr3nNc3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
