apiVersion: v1
kind: Secret
metadata:
  name: mam-session
  namespace: media
type: Opaque
stringData:
  mam_id: ENC[AES256_GCM,data:Hpwecwq07hLWkU1khAB4I/Qn4juIBCxi6oQscHi0SfrLK/6F99DxIwYjxonhUsnniAFbVI1BFDq5G+xQQHUyowOQEBz8SisoRu6xwSuAUkBNlDlcKAFE66C6ezPQbCk8b2ddSH/jkpSNb314Jm4I0voZYBlFaPyhhTdVjCpWYGYyB+p9Ai2dvNs1dUb0I2iuTh3seBDrEUYnhEpOK39tEclA7kut4QwP1NijbyaH4x1jqILejj9U57svnYCbPMDUosuzKtOg9SuSAkMYt6c1gCuxmCHOXQUjPmqCJc06fMmlBgUgg11hw49Jxu6N6XHmJdZ/nxJ8KzCObnjD8rV+Qv9R/XJuZy5lR8WxopVS/60gkG4ipRyPsXvKO4x15Q8NegXRUg==,iv:WTYlDX1wXb27LZ8551xLh4BnmZqoQxJm7WxOzaaGPMU=,tag:7EF5GstIqvRytGs/25QFbA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMzY1a3NGUHcyNVlNUkdt
        U1RkcFRwTUFsR2drNVFpdnlmc3E2bGIxR0VzCjlrRmY0eHBGRS9nM0xnMHZzSHZX
        Mjc0WHlKUHVEdkVwUzM4cExub0FuTG8KLS0tIFBFeTl3WjNTYmYzOEtqTkc5NlZR
        NFp4d0NRWEI4TFp6ZkJOdEVaZDJaNzgK+LNh8gjqH2UjRngLKHaxA4g7z82eowZY
        27Rj9hQLzMm2sMokytaaDFXmX23utrmvfcpvU0yqav3ziPXgCO6Wmw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYXo3dGN6cHp6VWhkVnFK
        dVVFMisrMmxkVHpRRU5VVTR5U1gycFF3TTFnClVsUzJNQ2xzUnVZU2tOM2dnRXBr
        L21xU3BtVDZndUk3dlpLQ3YreXNCcHcKLS0tIFJ0SFVGRjdER0RESHZ1S3Qxd1R5
        RDhBM2VJVTJ6bEwzSDBWVmhtb2hIbVEKOWnjW7nGVjzk49N9bw2yPxgYOagPd1gX
        gcerf5mTFXe8L15zoC1Lcy1f3m8om/kC6dUlHZBPbgS6k+YSDErS5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T18:49:07Z"
  mac: ENC[AES256_GCM,data:9F/c+e9NY8A5HiSJGTS8qrXFGFnkBUKg4uYou0uchVr35L018sF60FBeGvtrBi2iOx1FqJEJAbTHTKI8K8jK3sFvVHkwJv6xOAgILTOcIWyp1FqFZ+wT/oFyOA8YOlQYSfVVfRg5VN3FWKsdO9CTn6+jvVCoqJRQl7eCXb2lpu8=,iv:wqP+d6WPJeZMeobB61NYlbsdKpe+/iMBXMVpkjI3Ks8=,tag:GknwQLpoT8whQhu830i8FA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
