apiVersion: v1
kind: Secret
metadata:
  name: airtrail
stringData:
  #ENC[AES256_GCM,data:C0Np,iv:K0xeQy8mrv9Dfu2dTmLyERtzUPXYACaaFlfr5wo1z6o=,tag:Pz8gdRbgI9EstH8BwT80eQ==,type:comment]
  DB_URL: ENC[AES256_GCM,data:TjKzswQL9cvscX2Coz4ZgF9SOF0R7uzMeYtquaOP77xX4aQW9d61Jb3t4cVKY5b25VPiD5zA32YLlfF1qcWmCKGIBmYKaTGMEtLLltNZsBBLdDrh0qAcE+IKBQSkY81mD2c3VgDgJRM6,iv:fUhYO+j2YHMA2FWLJtW81DgiH3NmXPLclV2LQuNLr8I=,tag:enTsDXec6b3p7Ifz3PJEqw==,type:str]
  #ENC[AES256_GCM,data:GU8gRfN77mA=,iv:t3kZZYK8UmS5t3hVtSFibAnW4GmPNvwIrQVBmEoGuXA=,tag:EEO7bAR3ipQ6UdTeqVjb1w==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:GY+lxznsDBg=,iv:0eo9dyBNh/BsjJx6C1D7kRpRftYxUtUC8VGaRadWw7k=,tag:b5WF2AY88yFvT7H9hOO9pw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:pf3UH6FnAD5K3zhfFvd7JCe9Ue+ATbw9J8LhI6f1sjxNCc0WXec=,iv:IDlRyMPNakCrM9EwgSYza5gEU7SHNRsVSvVg/s09Fw8=,tag:jmrf7UQmXDs29y6Alc6pJQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Z57yYPYduSw=,iv:sfbHw+T4yRMNvGyDVNuI/eKOraKEz7HJZdteQeWa4yI=,tag:k90Ku5Cwe1gKRLX20co97w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dq4pbCJvffj0xHV9EUrSFuUT6hSfodS2S/pyFvhSZ1U=,iv:K/JmlXgy7Ul0piVv/8pLWrmQhRaIru3UFfM26odyqJs=,tag:j56/pkB7R1K0N+PNU07Vig==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:VYg=,iv:EzEcp01RTenkAIX6vehFBJJIQhEerB69lUJsLtV3rtA=,tag:SaOlq2ErvatAA/JIlLtzrA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OEeSksOx9eaaCw7+6KWDc0Drt/2FJ1VwMOK4ID53XYo=,iv:dBMfvO7rfovPRJQCJiSrxOCBgNDZTcFI4xlh4HXzwLM=,tag:tLFauOw2V/LKRAMVuCqkOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNG50TlJRMTF2RHZURUJX
        OThWQWgvVjhzU25ScXN4QmMrWlQ1aTE1Vmw4CldacDBDNlhQekFZRzhPV0tPVVVy
        VWhrRXJzMktGQ3JNWGZ1bk42SElPQ1UKLS0tIE5iQXJkREw3Tkx2Q1ErcFJ5Uk5P
        Q1h1U3FFbnN2NVlzd2hhZ0hNcHEvYncK/9xS8Gc3uSmQAu7duuQC9sUKINIggvRK
        4uUaNbOBTWwxgwuqysfQ/6hJhBTfqXCaoCkTZnCQexPLyXi6Ym8ohw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTnhXUWV4U1hkM21MZW5H
        N0s3SnMxM2NlSmh3MHBQNTdWY1VkTXg5NFFRCkYveGNZc0JxbG5MbytjS1RVVnNw
        empWaitMd0tKdE9qaGErVE1YZTJ5a28KLS0tIE14eUZUdzV5VnhVdDZYMkxJK2lC
        ZzQ1OTZBcWRBcXZ6dzFJVXp5Sjg1SWcKf+ITl3CQqXIiYy8DxUQVPpBVXbvP7QW3
        RSoHIkiCuU7dicuknpqBKCOZyA6Nh3+CTKFg8f2qlmLc86kPuytHWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T18:22:13Z"
  mac: ENC[AES256_GCM,data:/W7/hNuiJFVVdyYZVRRj47LQgmDQ0LQO/KNaA8rt48E0IfNH4E5s+Y0rlfg5cYsUsCG+STqvZ0Rfj7bsMdaBqk8njzpLdOiFI8bVNX2O78AOi4pZVeAegCa+AtSbOIMOuUOHuCxn8KoS44jXcCmSXQfRPs+68vQ9mAv9Ks4wouY=,iv:pHxTofUp3LV1R1qhMhg4niAL02MNgWUGvVisHwOt2fE=,tag:TCzr6M5sAD7HQChT//MrzA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
