---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: "external.${CLUSTER_DOMAIN}"
      recordType: CNAME
      targets: ["509ffe7f-bed9-4765-8a56-ae85427bfc22.cfargotunnel.com"]
