apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
stringData:
  #ENC[AES256_GCM,data:GB3nBA==,iv:J8XfbddKpEApltBErVBFvA9CXGk2SIfrTVJI84gyrRg=,tag:CnT7ya9Wr/kikC+oDk4G3A==,type:comment]
  PAPERLESS_DBENGINE: ENC[AES256_GCM,data:kSviDmSjyWid2Q==,iv:HhBPQbAZPA/Cdc3h4cfNDIX29oLkkGk69wKLaGuJZAo=,tag:Sxi+txqlgn6ko71N2K9nyw==,type:str]
  PAPERLESS_DBPORT: ENC[AES256_GCM,data:shpouA==,iv:pqs8y9w6I14QqK2tVVaOrzrcZYXPGFLgc5qfpQF2jRI=,tag:7Uja4smMnOv9zGnAFVaocA==,type:str]
  PAPERLESS_DBHOST: ENC[AES256_GCM,data:J4T61L3ggefLsa32wQQgj+Jc6kzqCez5LKZMrKMAQsTHYx8Vezc=,iv:OeYteIufeFJrKRM5pGxlb0pQOVLtWeq3Ugx/gmfyT7Y=,tag:qn+IgQ9lfuLNCQ+WqynTEQ==,type:str]
  PAPERLESS_DBNAME: ENC[AES256_GCM,data:7mUkR96CI4sq,iv:9g8uM/3tfzhAmiQpKmJj/inXxunV6lcvrINa8gwccU8=,tag:hhDa+nOEVN+sBg1szXbb+A==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:qj2gAd2bbHj+,iv:qXYjOT/X368E8TqTKmeft1nBRx09xSBBaoxDkwyOZY8=,tag:9dE96B2nSoNHmZSQUrQd/A==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:G33NNel7z5fCjGMJUYHEcdjcR54lXPuiRcLLZThprEs=,iv:JgSy91O93QJNTUymevuuifMqSvN8JeNWgvkEnZoDxcg=,tag:ho5G5Y06XKbgT6RqOyrMiQ==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:J590FhMHzmII,iv:VCvYPD++cw2Eh6H2L93pIyl0bcVI6+Oy3+P/i+GQspQ=,tag:sXqcWd4WiZY5sb0w4pr0nA==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:tlkgMwo4bPGp+t7jPLx9spG9xW4=,iv:fWVEWM0Un9CfVCE9/knBisN3EUfAiAYD6YQ3TRIVJ7k=,tag:dTfgj160O9jDOK6pYkTn8Q==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:by5zOpp0iTRjlufa/fnPUwp0XxKvyyopEejfWPtRkeuRyvJyD0SZ3eVdo8KNT6+g48P9V+gczZ3PNKJL1hIJ1vyA59ilzk3dQ+/SwmxmH2BX4UYe1Y8vlvJktJQ4ooPhlYarTEcotc2WVziszLTJZW+qAgU+GaVPWXApuAuvcm8=,iv:tzKR40WNqophZa6gGvAwPXLx3LGGFKRs+AmugJw3zQo=,tag:yl7+KuMCqTZXVJgb4ngEIA==,type:str]
  #ENC[AES256_GCM,data:4q7HT7yJcZrgVuUhl5A=,iv:pbdCb1wzu01rSSyb2QTCAO+BPxhmaBYHJ1FlUZUti68=,tag:oKFaZ18NhhINKbo58V7nHg==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9Xf/cj3k1Vd7,iv:ZeN7TiqDRnwlgyRIpNmWak76iqBvIYpItKO3L1euYQ0=,tag:RvGtuw8LAIh8+2PxQ/WiVQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:CCbBXF9Qla1iogXPQab165hCG/tF9+AG+/Qdn4ZvgtXWOlgUyU4=,iv:jIhDo8bJaL4ZpF609UtwE/Q+Jdy60arclFg9pYWvcZc=,tag:Z7rOu/QfLgdH21Ud1uWBGw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:HEZ/FTDouqck,iv:Ke3T4wGnKTI0gHnEH7iyOZAXCp8IoQMooUqsAvZZ5/k=,tag:s+Pap7SM0W3MxQi/6ByqrA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:gg8lEmSBlRMJyAcAXcFPDpw1DS8FWi3uU+IbRUlRIrc=,iv:bBFWXP9X/S+taKcN8mUq0Sp8WtFOpUEaGIcoPnPck4E=,tag:BiZcWNy92EkZ/pAvyjep1A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:xLKBxhSGGFm+4fj6EFgfQhEmQfciZ+mK4ALeKpN6gE0=,iv:M/CbA2EHhIviXpvcE3NkCW0TQl9NO7FvOv9uvRC1Y44=,tag:Cl099TXoC/rxv9FzoRzvhg==,type:str]
sops:
  age:
    - recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdkM5bTlrZUhmRy83WFhu
        MVh1eWdtTE0wNjhiY082S0ltSXJWZ2pyREZrCkJBeG1SZGFXNEFYdlJnTE1zMlk1
        SW5UYWRhbXFQZjIyVEloYTF3YzVvSFUKLS0tIGxlRXRaaUFMUnRWMVBORmhKcm40
        V1BoczZLUDNRR1grZi8wc1hhdGZKbTQKuwZGN95hW0ONn+nWSez3UmcLwvlFSMcD
        vySlEmN2Y0uKzoMGZiptGzmO+ZZ0Z2FIx5zk6YFWTK6bYl589IexHA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN20zZFAvVHNzZ0ZwNW1i
        Mll4d1ZmV3BheHYwaGI3UXUrUFZVeWd5UlNJClhaU0JQbm5IYlJwK3RDRUhKMXc1
        M3dQS2dNeWFPczlQNTlRV2ZCdEl2aEEKLS0tIENDQ2NERWE3SUdFM3BkK3UzODRF
        alM2T21VWjkyTFNnK3Urd0J0aTlFaEUKlKZEXiJwqeICpf/nCiwaikmMxFADCPIt
        bcFE+w1XCeIGNRehr+4YYQ5HflVMJgI/sSF2XrbvGBye7QwYiBoBjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-12T07:49:38Z"
  mac: ENC[AES256_GCM,data:SZHXbid6UNIU6LLHqvn7staQdlerBcxVErkrvEdMO+b0TYCwv6wx/IVESc9spKTfG10TAKpFkYRLxsRNcWsgXAT01vzhPNNh/b1Gdkod3Ripkt2ZMaQRixskRh7d/VwEojQsXzdzaqZT7Z0iGx6TjOCGEU+Tq5gre6FSYBp7gAU=,iv:zAKo/NCzIs5KAHQgxRB+52iNu7hMXTBX9yRyluHSF28=,tag:10Zfbb+KqQEMb3hgTVdwUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
