# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: adventurelog-secret
  namespace: default
type: Opaque
stringData:
  DJANGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:rS+aWk8qgW3yD131liz8Sw==,iv:2MAGJ+yh9X5SbIP+XaxTP02F4czyrAGRbz17WjyQZ7E=,tag:X+i24bdWoG28/dRcGLZ2DA==,type:str]
  DJANGO_ADMIN_EMAIL: ENC[AES256_GCM,data:BfK4fMpXAwnLDjPDZVGNlOWAUKWv9VFj,iv:7KwkwIijxD7nzhwj+NM9KDdAwMhImXiUIwtT+r71d9g=,tag:E1wJkDJsr/wJhxwB0Nu8QQ==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:PvnBU2SbQg1xbjd3KFIaR7h+1P128BFckzUKGAkYGpfTRMb5FITK/iFz6fvRoKhC0pvpnRodPnBts4prfOjnYQ==,iv:iPzmunEV8eU5xlzBh2mZKSIqJu3ZlwWOYlzRnWaapoo=,tag:slYls42gzNfkNq3uf5hzOA==,type:str]
  PGHOST: ENC[AES256_GCM,data:LfMsBaQa+Z3uty2grmYReYcQAuCyFl++D9ZZyIBdCQ74nx/7ZFo=,iv:rBs8VIoLnMJrkf73q7IiQukbOB6YFrYeKA+coBmwWpE=,tag:DjONIgQNTumCN9IzEdILvA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:fS13rVxM8qpbxOZ2,iv:P78O8gTR0E8eh6FVHCQAlq8tL4tC1PoGcUIyJEblg6U=,tag:nqFCCY7F42wxz+OTZXtxvg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:Eby4LIdQpPuINIRO,iv:FxRg/mDDa02IFgTILa8lmc0z0zASms6K+ZQuHSThNj0=,tag:xUOicTnSO1qv46FcCgeppQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:cCHErPDBQSBggrfMyLtN5sgQMvfsicy9M0vBhlGVayo=,iv:tm80OB25OfvfbVPf6NY2QxcwgwZZ7fWQ/Vl4TnHZ36U=,tag:QgedYhMDg5Es3xuZNxfrxA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cl6G6Vq1WXaFe4UO,iv:5CXni1OqKtNuIL/BHhzVQRqRdyC8Sl35tnKtVto2Src=,tag:T9p/Yqkrgp/wFOTX/NEViA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:R0Z6c/n3FyB9eITv9jUecjcvBMp6x0UJsKorEf5d06o6DDneqjw=,iv:FGkmpoUmtWHE89lsp1TLjG1iLS6EvndZObBw/BP0lsE=,tag:aG/rdpDY5ffUT/lT8D5Mug==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:1yKOxxYokC3Qh1D7,iv:uyaJu0aL/HGY1szrKKiJcW1ckyYZW2njxiQbRnwWx10=,tag:ORE8FB9IHgvs+EuULL9wTA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GXWej+H0p0EqqUCGUXDx6AB1LbBMDQhI4DWD+3iwVLU=,iv:tmhSwA9Is853M0izPCO+Iu/Xkt/AawvYW2iug8g2JXw=,tag:Rabfuhxq0cFFUbFA7Ro10w==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mWaam98Ke8Sni2TA8qF1Hlq240bpr095E979VYg5/u4=,iv:dcdItd34m4jeGTvj7d7a8Eu8rN+m5xaAUll9JREn7bY=,tag:dScQn3ZAw+4hfyYRWVILTg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeWc0Qk1hTDBtN3JZSkNP
        bEdweExLRmlaT3V6UWVSLytyU2RKL1hMUjFRCkxvdm9rVmhiY3JOYnpKS091N3d4
        WmNweVVmNWg0NndEN1NhS2ltR3RUaHMKLS0tIGVaOEJuc0lmdkJkNDhYUWpuYk52
        ZVlwNXdqNW9ZdG1PSkJiU041UFNLRGMK61SvC3SrEB60mxoSb78TEPuTkTTrglrh
        IGr2sF1MAVQS/6WeXyjuYd2kcHhFPJn9Q6pSpEmrWKb3FcwDoJMPOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXlmY2twT2pzcHFLVjNR
        Z2lUT2FncjJ3RmpUc0ZwMDNIaFYxNS9IM1ZRCitHTWRRbEEyTmUxU2JKc3FGcEN5
        eldZU29XejkwaW1GakZEOG81OUV4Y2MKLS0tIGxxQkJ2b21WR3VGZFoxdTBaWUxk
        SjFSZUZNMDNrc050NTlpcllOb3M4bFkKCr1qqxB52PSosnH2X1ud5RyLcpZIRf8l
        Dr93RYSz7gfG9kSdZnTMN1yHBq2BfRTSjV91oBB4gvCAUwBhcKlocQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T19:48:44Z"
  mac: ENC[AES256_GCM,data:RxaDvXqSXcaQ/P4g+ko7o5qoTvTxosJAtYZCwwBFETw+DV3OmY837VrWQuzCHe/YTtfQD63ysh0zGdnQ6iDwY9MBb323nayUfkG3yRzf2d6HmDUuyb3MxICcbESK0k76ePp+i4pFnux6Pign0EG7yE0FlF+d9wJqUUBL2ndZbtE=,iv:bwn9nWdI4a5dDR9NNbmxzB2smarsoglViwzwYWdWmxo=,tag:nOgJpIr8X8+AcVbtO2mTrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
