# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:AS8ge7gwoiHjOiBJjr7rPB8fIhPa4ffRHSWupnAQeUI=,iv:4Mo4GBZcjUTENlBwYQDQGb91l869H5TKixvi7a3kpFM=,tag:/F0xVbQ7ohVbkLCQUVTCIA==,type:str]
sops:
  age:
    - recipient: age12na74smcu3ww2gaglv8spqwur29d7gqax83u00w9rs0t0yw2eqlqc249je
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmM2MmZvR0hOa3EvQStt
        aHdHY0JxamZvWWtpOUorVG5RVURTbmdMTVE0ClZ3UFY4L3pTY0dTeGlSQlJjeW1h
        RUt1M0NyUDE3UHdVekVNZ1YzNVJNRGMKLS0tIFJBUXZJbTJybERubWcvc1JZQjQr
        OGRBRDZoa0d5eTk1OENzTC9EWlgvLzAKa4cI1E5LrPk5zY2k3WTVLFSSs+8gxmpf
        5B8xnu/qFz/nfhVO4GcqojBnxTtTC2tm7qdW7paBMoBIYJSWAw4asA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-20T10:08:05Z"
  mac: ENC[AES256_GCM,data:DQk1V2Cer3CSvvskManEmoO26k3ECMQGTlIHOZffmKqrgoWpBvln//2vKyGpiTwnwqAX1CWVZIISgBwflCVeA4Q+SDPICAhMAuFO4CG878OESSqRxKfKSsbo+EMFwOjgZjsUVrwdalPDgHKXfHeaAJAv68ur4hTMR8f0fhbI9nE=,iv:pYrGe5zXwTK1HrQBPKfqIxWNa3E8EvoqffS65njgUCk=,tag://Q3LPUC2XU8pukkzr3hjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
