# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: readmeabook-secret
type: Opaque
stringData:
  POSTGRES_DB: ENC[AES256_GCM,data:BycQKur9m8i1YbI=,iv:ZAqnI7jKz3yFPnHYINvtuwDMuo4SqKKEUpZFXtk2tbc=,tag:ZzLCXgoEimYVtST/L56D+Q==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:c6z/nudQ296zHGLp4Q03ub9m1xiT8ktj6R9hvC6ZD21BVpuvqYI=,iv:DqzuPEOaOdt6IFbqz/I8LR51uNQRjenkJzlBd7AVVAs=,tag:12X5j1gcN+e7DrnHp6oQ7Q==,type:str]
  DB_PORT: ENC[AES256_GCM,data:XDNX2w==,iv:UC8bCmpaLSkqjRF08EbUgzFJx9u084YamAGK0EJFb8U=,tag:ZhQBkX7kU+A4I0pOkkMtVw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:A0bjJfV49tmCQ/Q=,iv:AtCesW8bVzxs1Yo1RbX6FDYcl5d4eaMGPPk1suN7v70=,tag:0ySvEMNSlhD7IYVfyVQYBg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:wZZf3ZyFXQ/UYtPhG9jBVQ==,iv:Sg5/Hr0LfVddhqCbodB1nY1DXE0b1yhbIbN2XxMm2ko=,tag:YwGr48yJC0MwYcUGaGRIIQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:Q27p/JCsL4+TnPe9YesDsJ0OByn4l6LHqNLjGfsySc9yfFoP4FkVDP1EpGfum0HRhuwtGNlaLl6kN9flJpXNBwlK6eK1jiHbYH/eDNJ0Gc7nN5fHL69TmacrzumcXXz9Gw==,iv:m5mr8w1O9QZ06Vls4IS0ABiVRG/3lfRUne7Iy1oy21w=,tag:WQWEJaf3jQssCC+IurAfig==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:ZUhRuOXb897e8ow1G5MDMcX3xJOLpbhvZjruKWQOEQbK0JQnhvgDiUy86RxY/WyuUOwt771mE9y7KWhkqbG6Lg==,iv:IHjseEOBGp/Ve5zm3f94JktijocHMk2BGdCCjnVWJbU=,tag:z0OMWHFZO2FFgBhx/kR5jg==,type:str]
  #ENC[AES256_GCM,data:AcPKjt8cHtfQOrnXybs=,iv:bNaKXHeQCDOlI9mi/bkRYuNgDGiVjjb9LXESWpIOuvo=,tag:xVeKqrtvBV1KkBra2d0l8g==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:CA8QAvSirbfthuo=,iv:opf2fXfjn9j7L3Y0zVXHItuN77Cxopm7/QTxfoIX01k=,tag:Wy9WVVNC1uxKu0rNRzLAPg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:lJRENQTOEDsm5LIZmEtbxMtIVX3cEAysKCepOg1r+Sv87j0z39Y=,iv:nZdl+TgvTlF3x/QS2WOgrgQ6Y6Q1g5FPOh9o9tPmln4=,tag:sHTgjvqKP+LD9F0FURvr0w==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:BpVLCrp3yqbkx3M=,iv:eetLY3942AtDN4Kc3Ow9PogMH/3WLWkr4wzEf2Wk2EI=,tag:+F+BHpAgoFrwguCXTgYnYg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dIoX83N4Hh+TYeJrw8ld6Q==,iv:0lQqZFWCEpDBbQUtzXI6EqeAVQbuHLmIrxsg2s+RXIo=,tag:/sYGKeTxCU7djgiCK9thpQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:xP2xBTh3pKpi9xXTPOLn+fda8WX71X584+1tebhyDtM=,iv:zj2xsHO0ER1gtE39Al/ZFzqlaq8qChXoepajAdzSNDQ=,tag:LMwio1N3pVTfnvZhuxTHnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSDFYd05CRm5ad293TWkz
        L0dIYjBzZWlNYlFDbzVuRW5scDlrVjJvekhvCk05Q1NyTnhDdk9icmJaNEF0YXV4
        akYveWh6RHU4anBTTnIwMk5UMkNnUUEKLS0tIE9RWFd6bVhXZmpvQ0JOU3RCQ1pM
        NFhad0FUSUU5SW9XcEd5ZzlyQWR6MmsK020nzlMCehTQU3M+sf8OiNptMes2JW4f
        AeUcAaJZRYFRkwDfg/VYdic3hxOF29ej2cPN46964vVJiUflY8doXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1npm76t7g67zlgjmkpppetysk66m4vaf8jstm22cmwv9phm0zxe9qdfye33
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN1BnMTUweGZGU0FmS2Ux
        aTJSNGtaMUJPU1p1ZCsrY0lFUlJBQWZNbGk0CmpOcCtIZmFjV0hMTWozVW1lSUZy
        dTJtUjZBQWNIRTU0K0h5OVpQbWN5M2sKLS0tIFlSS09rL29CalhaOGUxZFNOc1FR
        b05oaStyZjU2ekFSc0FabjRTZEE5M0EKsd7gsaexMLor3pyF+K6KwkPxdk3nMrBf
        2b3FJMO+gzTTUSvgVz9dzoGiz5Am0tHi3leU5CiRsTlEuSE7a63evA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lm9yjzpt3a5wrk3k5qn6ahkj5qmqyttmk6vn7cadxydrwew0cflq2xlzhe
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-10T19:52:37Z"
  mac: ENC[AES256_GCM,data:BG1iUXQyELwIN7JoB2GO7pie4pegkeCCXFG6vIG42M+bNi3geV8liF0HxiCOspLdvMLQbrMjo68B92kUdPjH12pOrESzc/hyB5szUfymyWE3tpkdzyS785O/mlOW20hm2uP6Lja7yL5f+44tpSwDFMFpL6zZVajkgPYX5TOWyd4=,iv:gQxaM7xIEeRv1ymNL2/EAmjDaZ2SOdTaer4281tS9a4=,tag:KA3LNXKzEE8CSAxeC4bbdQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
