# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.10.210:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.10.210"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "cafe-optidesk-1"
    ipAddress: "192.168.10.1"
    installDisk: /dev/disk/by-id/ata-Seagate_BarraCuda_Q1_SSD_ZA480CV10001_7RV00V34
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e4:54:e8:73:a2:04"
        dhcp: false
        addresses:
          - "192.168.10.1/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.10.210"
    schematic: &intel-schematic
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: &optidesk-1-disk "'/dev/disk/by-id/nvme-CT1000P3PSSD8_24534D2F096C' in disk.symlinks"
          maxSize: 800GiB
          grow: true
      - name: ebs
        provisioning:
          diskSelector:
            match: *optidesk-1-disk
          minSize: 10GiB
          grow: true
  - hostname: "cafe-optidesk-2"
    ipAddress: "192.168.10.2"
    installDisk: /dev/disk/by-id/ata-VK000480GXAWK_21203027BB38
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:4e:01:9e:f2:11"
        dhcp: false
        addresses:
          - "192.168.10.2/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
    schematic: *intel-schematic
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: &optidesk-2-disk "'/dev/disk/by-id/nvme-CT1000P3PSSD8_24534D2F0964' in disk.symlinks"
          maxSize: 800GiB
          grow: true
      - name: ebs
        provisioning:
          diskSelector:
            match: *optidesk-2-disk
          minSize: 10GiB
          grow: true
  - hostname: "cafe-optidesk-3"
    ipAddress: "192.168.10.3"
    installDisk: /dev/disk/by-id/ata-CT480BX500SSD1_2036E4AE1C94
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e4:54:e8:70:76:e4"
        dhcp: false
        addresses:
          - "192.168.10.3/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
    schematic: *intel-schematic
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: &optidesk-3-disk "'/dev/disk/by-id/nvme-CT1000P3PSSD8_24514CF148A9' in disk.symlinks"
          maxSize: 800GiB
          grow: true
      - name: ebs
        provisioning:
          diskSelector:
            match: *optidesk-3-disk
          minSize: 10GiB
          grow: true

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-kernel.yaml"
  - "@./patches/global/machine-udev.yaml"
  - "@./patches/global/machine-features.yaml"

controlPlane:
  nodeLabels:
    intel.feature.node.kubernetes.io/gpu: "true"
    node.longhorn.io/create-default-disk: "true"
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
