# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.10.210:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.10.210"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "cafe-optidesk-1"
    ipAddress: "192.168.10.1"
    installDisk: /dev/disk/by-id/ata-Seagate_BarraCuda_Q1_SSD_ZA480CV10001_7RV00V34
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: true
      node.longhorn.io/create-default-disk: true
    machineSpec:
      secureboot: true
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e4:54:e8:73:a2:04"
        dhcp: false
        addresses:
          - "192.168.10.1/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.10.210"
    schematic: &intel-schematic
      customization:
        systemExtensions:
          officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
    patches: &secureboot-patch
      - # Encrypt system disk with TPM
        |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: &optidesk-1-disk "'/dev/disk/by-id/nvme-CT1000P3PSSD8_24534D2F096C' in disk.symlinks"
          maxSize: 800GiB
          grow: true
      - name: ebs
        provisioning:
          diskSelector:
            match: *optidesk-1-disk
          minSize: 10GiB
          grow: true
  - hostname: "cafe-optidesk-2"
    ipAddress: "192.168.10.2"
    installDisk: /dev/disk/by-id/ata-VK000480GXAWK_21203027BB38
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: true
      node.longhorn.io/create-default-disk: true
    machineSpec:
      secureboot: true
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:4e:01:9e:f2:11"
        dhcp: false
        addresses:
          - "192.168.10.2/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
    schematic: *intel-schematic
    patches: *secureboot-patch
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: &optidesk-2-disk "'/dev/disk/by-id/nvme-CT1000P3PSSD8_24534D2F0964' in disk.symlinks"
          maxSize: 800GiB
          grow: true
      - name: ebs
        provisioning:
          diskSelector:
            match: *optidesk-2-disk
          minSize: 10GiB
          grow: true
  - hostname: cafe-vm-1
    ipAddress: "192.168.10.3"
    installDisk: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0
    machineSpec:
      secureboot: false
    controlPlane: true
    nodeLabels:
      node.longhorn.io/create-default-disk: true
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:84:56:d1"
        dhcp: false
        addresses:
          - "192.168.10.3/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.10.210"
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: &vm-1-disk "'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1' in disk.symlinks"
          maxSize: 100GiB
          grow: true
      - name: ebs
        provisioning:
          diskSelector:
            match: *vm-1-disk
          minSize: 10GiB
          grow: true

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-kernel.yaml"
  - "@./patches/global/machine-udev.yaml"
  - "@./patches/global/machine-features.yaml"

controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
