---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
data:
  # URLs
  IMMICH_WEB_URL: http://immich-web.default.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.default.svc.cluster.local:3001
  PUBLIC_IMMICH_SERVER_URL: https://photos.${CLUSTER_DOMAIN}
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.default.svc.cluster.local:3003

  # REDIS
  REDIS_HOSTNAME: "immich-redis.default.svc.cluster.local"
  REDIS_PORT: "6379"

  # General
  NODE_ENV: "production"
  LOG_LEVEL: warn
