---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: immich
          configmap.reloader.stakater.com/reload: immich
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.1@sha256:866f15038ed5185a2b8118821f470bb7ca0df8c4231b8e277446e681ebb1ed84
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: immich
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
            envFrom:
              - secretRef:
                  name: immich
              - configMapRef:
                  name: immich
      machine-learning:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: immich
          configmap.reloader.stakater.com/reload: immich
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.4.1@sha256:b3deefd1826f113824e9d7bc30d905e7f823535887d03f869330946b6db3b44a
            envFrom:
              - secretRef:
                  name: immich
              - configMapRef:
                  name: immich
            env:
              MPLCONFIGDIR: "/cache/matplotlib"
      redis:
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.4.0@sha256:73dad4271642c5966db88db7a7585fae7cf10b685d1e48006f31e0294c29fdd7
            env:
              REDIS_REPLICATION_MODE: master
            command: ["redis-server"]

      public-proxy:
        containers:
          main:
            image:
              repository: alangrainger/immich-public-proxy
              tag: 1.14.2
              pullPolicy: IfNotPresent
            env:
              IMMICH_URL: http://immich-server.default.svc.cluster.local:2283

    service:
      server:
        controller: server
        ports:
          http:
            port: &port 2283
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
      redis:
        controller: redis
        ports:
          http:
            port: 6379
      public-proxy:
        controller: public-proxy
        ports:
          http:
            port: &proxy-port 3000

    route:
      internal:
        hostnames: ["photos.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: server
                port: *port

      proxy:
        hostnames: ["img.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: public-proxy
                port: *proxy-port
            matches:
              - path:
                  type: PathPrefix
                  value: /share/
              - path:
                  type: PathPrefix
                  value: /s/

    persistence:
      matplotlib:
        type: emptyDir
        advancedMounts:
          server:
            main:
              - path: /config/matplotlib
      library:
        existingClaim: immich-nfs
        advancedMounts:
          server:
            main:
              - path: /usr/src/app/upload
      machine-learning-cache:
        existingClaim: immich-machine-learning-cache
        advancedMounts:
          machine-learning:
            main:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache
      tmpfs:
        type: emptyDir
        advancedMounts:
          server:
            main:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers
