---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - configmap.yaml
  - immich-ml-cache.yaml
  - immich-pvc.yaml
  - helmrelease.yaml
