apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:VflDU0RClJkiGrOLLxOw,iv:+63nKpVYdRyab2VqXasWaeK5FzBpItGrH/ZfnoVHm7c=,tag:/7rfkDHTsIOyAKzeoyFLlw==,type:str]
sops:
  age:
    - recipient: age12na74smcu3ww2gaglv8spqwur29d7gqax83u00w9rs0t0yw2eqlqc249je
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUDBFdTJPaGZ5VlNleXAy
        Q2NRbUU5V24zOVlNUitjbnorbFJlUmQxZUNBCnRuSEJaeHhVVjM1R1paWk4rVjVU
        NVcwdWZtLzhDeDJwcUZiSk1ic2JSb28KLS0tIHlFQkNYYktHQzBsR2J1SjZjbEJp
        N3d5WjBnU1BLZkRmVTF5MFJKRUVweW8K4HqAhGtyiuGBbjqyBnhMWQzK6Un6mMH6
        u1rdtxIsDxH+7+4BJvVi0kSblHinAoxjlHNzyR3+XId5Asx9pbOi4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T21:44:54Z"
  mac: ENC[AES256_GCM,data:bs2Qzi2ISGZK61TQvRjctR4YIU19DUwx4h5dKCEMQ1OuB7BiZkesDzBVjLKi1uA8J/BVVTTyXTkGeoApLuZvkzal0/Eommv0rueihz8EQDjXxfvDDWTg1lB2Tost3Va0ZX2Y4N6mjZJJvX/zf71ZvrVPQ7YJArVotx4XCZdJh9k=,iv:tt4WZOSX/SHtgklehY1eXH8KJ7vqelrpJt7ZpB+yAT4=,tag:amRbh1axv5EZKMKDGNjQNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
